# Generated by Django 5.2.7 on 2025-10-25 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, unique=True)),
                ('capital', models.CharField(blank=True, max_length=255, null=True)),
                ('region', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('population', models.BigIntegerField()),
                ('currency_code', models.CharField(blank=True, db_index=True, max_length=10, null=True)),
                ('exchange_rate', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('estimated_gdp', models.DecimalField(blank=True, decimal_places=6, max_digits=30, null=True)),
                ('flag_url', models.URLField(blank=True, max_length=500, null=True)),
                ('last_refreshed_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Countries',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RefreshLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_refreshed_at', models.DateTimeField()),
                ('total_countries', models.IntegerField(default=0)),
            ],
        ),
    ]
